-- Add RECEITA_TEXTO and SOLICITACAO to SignedDocumentType enum
ALTER TYPE "SignedDocumentType" ADD VALUE IF NOT EXISTS 'RECEITA_TEXTO';
ALTER TYPE "SignedDocumentType" ADD VALUE IF NOT EXISTS 'SOLICITACAO';
